/*
 * ultrasonic.h
 *
 *  Created on: Oct 16, 2023
 *      Author: fatma albaz
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_
#include "std_types.h"
/**************************************************************************************
 * 									DEFINITIONS									      *
 **************************************************************************************/
#define ULTRASONIC_TRIGGER_PIN_ID			PIN5_ID
#define ULTRASONIC_TRIGGER_PORT_ID			PORTB_ID
#define ULTRASONIC_ECHO_PIN_ID 				PIN6_ID
#define ULTRASONIC_ECHO_PORT_ID				PORTD_ID

/**************************************************************************************
 * 								FUNCTION PROTOTYOES								      *
 **************************************************************************************/

/*
 * function description:
 * this function is used to initiate the ultrasonic driver
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void);
/*
 * Function description:
 * this function is used to send the trigger pulse for the trigger pin
 * the trigger pulse is high at least for 10 micro seconds
 * this is done by producing a high value on the pin then delay for 15 micro
 * seconds and then return the pin value to low
 */
void Ultrasonic_Trigger(void);
/*
 * the distance range of the ultrasonic is from 2cm :400cm
 * so the distance data type will be uint16
 * the distance is equal to the speed* time
 * time is measured from the function Ultrasonic_edgeProcessing
 * speed is the speed of sound 340 m/s
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);
/*
 * this function is called when an interrupt request is initiated (the required edge is detected)
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);
#endif /* ULTRASONIC_H_ */
